lark:
  endpoint: https://open.larksuite.com/open-apis  #Alternative with https://open.feishu.cn in China
  app-id: cli_xxxxxx
  app-secret: RGExxxxxxxxx
  authorization-type: INTERNAL_APP #see org.microjservice.lark.core.auth.models.Credential.CredentialType
  encrypt-key: 114514
  auth-patterns:
    - "/open-apis/contact/**"
    - "/open-apis/chat/**"
    - "/open-apis/message/**"
    - "/open-apis/auth/v3/app_ticket/resend"
    - "/open-apis/im/v1/messages"
    - "/open-apis/bot/v3/info"
#    - "/open-apis/auth/**"
jackson:
  property-naming-strategy: SNAKE_CASE

micronaut:
  http:
    client:
      read-timeout: 512s
  server:
    port: 10086
    netty:
      access-logger:
        enabled: true # Enables the access logger
        logger-name: Lark_EVENT_LOGGER # A logger name, optional, default is `HTTP_ACCESS_LOGGER`
        log-format: common # A log format, optional, default is Common Log Format
      log-level: TRACE
    host: 0.0.0.0